### PR TITLE
Add F#

### PR DESCRIPTION
**Pull request by purkhusid**
## What?
This PR adds the following:
* Updates rules_dotnet to the latest commit for .Net 5.0 support
* Adds F# Protobuf/gRPC support using https://github.com/Arshia001/FSharp.GrpcCodeGenerator
* Adds Routeguide example for F#

### CODE REVIEW

**Comment by purkhusid** [comment]
This is ready for review

**Comment by aaliddell** [comment]
Wow, awesome! I'll take a look at this on the weekend or sooner if I get a chance.

I still need to get back to you on platforms/toolchains topic on rules_dotnet, but I need to make a demo repo to check it

**Comment by purkhusid** [comment]
> awesome! I'll take a look at this on the weekend or sooner if I get a chance.
> 
> I still need to get back to you on platforms/toolchains topic on rules_dotnet, but I need to make a demo repo to check it

Sounds great! I would love to find a way to configure rules_dotnet without platform flags that also works with `target_compatible_with`

**Review by aaliddell — APPROVED** [review]

**Comment by aaliddell** [comment]
Merging into dev in advance of 3.2.0. Thanks!

**Pull request merged**
