### PR TITLE
Add options_override argument to proto_compile_impl.

### PR DESCRIPTION
**Pull request by gonzojive**
options_override allows passing dynamic options to a plugin. This is currently needed by rules_ts_proto to pass a per-invocation configuration object to a plugin; the configuration object being passed is a mapping of proto path -> js import path.

The options dictionary also now tolerates Label values as keys instead of just strings.

See https://github.com/gonzojive/rules_ts_proto/commit/24460f5929c73db87f6a49f65240cae16888d2ad for usage.

### CODE REVIEW

**Comment by gonzojive** [comment]
Any comments on this PR?

**Comment by aaliddell** [comment]
Sorry, haven't had time to look over this repo in a while.

Can you not just call `proto_compile` directly (rather than `proto_compile_impl`), which already lets you pass the options as an arg rather than via `ctx.attrs`? e.g how it is done in `doc_template_compile`:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/1c9e81538467d3809dbf4035007397138a015583/doc/doc_template_compile.bzl#L11-L29

**Comment by gonzojive** [comment]
> Can you not just call `proto_compile` directly (rather than `proto_compile_impl`), which already lets you pass the options as an arg rather than via `ctx.attrs`? e.g how it is done in `doc_template_compile`:

proto_compile is not exported by defs.bzl. I could change that if you like.

**Comment by aaliddell** [comment]
Alt fix has been merged in 4.4.0. Let me know if it isn't working as desired. Thanks

**Pull request closed without merging**
