### PR TITLE
3.0.0 release

### LINKED ISSUE #20: Add support for C language
Is it possible to add support for `c_proto_library` via https://github.com/protobuf-c/protobuf-c?

### LINKED ISSUE #25: Cannot depend on two overlapping cpp_proto_library()'s
If you do this, then bazel will link in two separate (merged) directories. At best, this will cause ODR violations at link time; at worst, it gets caught at runtime (I found it when compiling with ASAN to debug a segfault caused by it).

Essentially, if I have a `cc_binary` that depends on a rule at `//path:proto_one_cc`, which is a `cpp_proto_library()`, and another rule at `//path:proto_two_cc`, and they both depend on a `cpp_proto_library(name="common")`, then I'll get two instances of every linked object from the common proto. Typically, this will include things harmless like the default instance of the protos, but also various static objects like descriptors that are compared by pointer (because why would you have two descriptors for the same proto in your binary?).

One way to avoid this is to make the `cpp_proto_library()` also an aspect, not just the `cpp_proto_compile()`, and switch to `merge_directories=False`. That aspect would be able to grab the includes from all its dependencies, transitively, and add those to itself. It would then return [`CcInfo`](https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html) to be part of a [C++ compilation natively](https://docs.bazel.build/versions/master/integrating-with-rules-cc.html).

### LINKED ISSUE #31: Only Build gRPC Protobuf with the gRPC Gateway
The `protoc-gen-grpc_gateway` plugin generates gRPC gateway from *gRPC* protobuf files. 
Consider this example:

**service_a.proto**
```
syntax = "proto3";

package service_a;

message TestMeServiceA {
    string name = 1;
}
```

**service_b.proto**
```
syntax = "proto3";

package service_a;

import "google/api/annotations.proto";
import "service_a.proto";

service TestService {
    rpc Echo(service_a.TestMeServiceA) returns (service_a.TestMeServiceB) {
      option (google.api.http) = {
        post: "/v1/example/echo"
        body: "*"
      }
  }
}
```

`service_a` only hold a message. `service_b` reference to `service_a`, and also define gRPC request that use the message defined in `service_a`.

When trying to build the gateway against it, Bazel will complain he can't find a file called `service_a.gw.go`. Checking the final DepSet, there's 4 files:

- service_a.go
- service_a.gw.go
- service_b.go
- service_b.gw.go

(the reason is generated two files for each proto is because the [gateway_grpc_aspect](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/github.com/grpc-ecosystem/grpc-gateway/gateway_grpc_compile.bzl) defines both go and grpc as plugins).

However, the `gateway` plugin, will not create a `*.gw.go` file, when the file doesn't have gRPC definition (it's doesn't print any error, just doesn't create anything).

So the real files created on the filesystem would be:

- service_a.go
- service_b.go
- service_b.gw.go

That's why Bazel complains about missing `service_.gw.go`.

### LINKED ISSUE #40: Public headers must be in `hdrs`, not `srcs`.
Currently generated proto headers for C/C++ are in `srcs` ([code](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/8c8aab86c761ba762477128f121e12974e14b497/cpp/cpp_proto_library.bzl#L14)). Since these are supposed to be "public" headers, this is incorrect. See [documentation](https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs) for explanation.

> Headers in srcs must only be directly included from the files in hdrs and srcs of the library itself.

The current implementation works by accident because Bazel doesn't enforce the distinction between public and private headers.

### LINKED ISSUE #54: Adding 'Options'?
Is there a way to add 'Options' to a plug-in without modifying the project's BUILD file? Passing it as argument when defining the rule? was thinking about something like that:

```
scala_grpc_compile(
    name = "test",
    options = [
            "java_conversions",
            "grpc",
        ],
    deps = [":testl_proto"],
)
```

We need to use `java_conversions` here, but I'm not completely OK with adding it to the scala BUILD file, as while it's very popular, not all user will want to use it.

Thanks.

### LINKED ISSUE #55: Creating a JAR With No Dependencies?
At the moment, when building a Java Library, all dependencies are being included into a single artifact (JAR). For example:

```
proto_library(
    name = 'test',
    srcs = ['test.java'],
    deps = ['://dependencies:java_dependency']
)

java_grpc_library(
    name = "grpc",
    deps = [":test"],
)
```

The Jar that will get created will have both the `test.java` class, and the `test2` classes. This is kinda goes against how `java_proto_library` works. The reason it's important for Java users is due to dependency management. Let's say for example I have two Jars. One would be `test` (the one defined above), and another one called `test2`. Both have dependency in` ['://dependencies:java_dependency']` - but one Jar was created a week ago, and one Jar today and include changes in `['://dependencies:java_dependency']`. When both Jars will load, JVM will randomly pick one - and that's a problem.

EDIT: Well, this is more complex than I originally thought. 

```
        DefaultInfo(
            files = depset(all_outputs),
            data_runfiles = ctx.runfiles(files = all_outputs),
        ),
```

It looks like all the Provider returns all the chain of dependencies. I'm assuming that's on purpose, so you won't have to re-define the same deps on target that use the rule. So while makes writing Bazel easier, it's a problem with Java. Maybe it's worth considering adding a 'Transitive' flag of a sort that defines if the return value form the rule return all transitive dependencies - or just the head.

### LINKED ISSUE #59: grpc-web rules should support text (as well as binary) format
Based on [the grpc-web docs](https://github.com/grpc/grpc-web#wire-format-mode), server streaming over grpc-web is only supported by the text mode format.  Currently, the grpc-web rules always use the binary format (see [here](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/github.com/grpc/grpc-web/BUILD.bazel)).

The grpc-web rules should include an option to request either the text format or the binary format.

     mode=grpcwebtext

or

     mode=grpcweb

### LINKED ISSUE #67: ruby_grpc_compile fail if the proto file depends on another internal package
Hello!

We're using `ruby_grpc_compile` in our project (thank you for these rules!). And we've recently run into an issue that has been a blocker to our project. We added an internal Protocol Buffer to represent the response status, and it broke `ruby_grpc_compile`.

For some reason, Bazel expects the dependant proto to generate `{proto}_services_pb.rb` but it's actually generating `{proto}_pb.rb`.

I have filed #66 as a reproducible example, and it includes the commands I ran as well as proof of the afore-mentioned confusion on the output naming.

### LINKED ISSUE #68: Support passing options to plugins though a separate flag
For example [buf](https://buf.build/docs/lint-protoc-plugin) requires passing it's config through `--buf-check-lint_opt` instead of `-buf-check-lint_out`. This aspect doesn't support passing options though a non-out argument.

### LINKED ISSUE #72: Rules for grpc-gateway only work on proto files without imports
If I add an import to a file with a grpc-gateway service it fails:

```
output 'github.com/grpc-ecosystem/grpc-gateway/example/api/test_proto/gateway_grpc_compile_aspect_verb0/github.com/grpc-ecosystem/grpc-gateway/example/api/test.pb.gw.go' was not created
```

### LINKED ISSUE #85: Update protoc-gen-go-grpc
There is a new version of the plugin to generate gRPC code for the new Go protobuf implementation. Details are here https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0

You probably know this, but I thought I just create an issue anyway to get a notification when the support for it is added. Thank you very much for this set of rules, it is very useful!

### LINKED ISSUE #93: OpenAPI v2 annotations
Hi,

As the example and repository files show, there is nothing mentioned about `protoc-gen-openapiv2/options/annotations.proto` exist in in `grpc-gateway` repository.
is there any example on how to use this annotation file for generation swagger definitations?

### LINKED ISSUE #105: Add support for "--experimental_allow_proto3_optional" protoc option
I'd like to enable [the `--experimental_allow_proto3_optional` protoc option](https://github.com/scalapb/ScalaPB/blob/master/CHANGELOG.md#0110-m3). Maybe this is already possible, but I was not able to figure out how.

### LINKED ISSUE #108: Rules_scala removal of proto deps broke scala_proto_* rules
https://github.com/bazelbuild/rules_scala/commit/e9dfbe39fa44a8dc7ab0b9aef46488f215646d9c#diff-880cb55f92402ecc802bce095bcb3e5664f04bc34031e8d33dde1f0b6f239c6f

### LINKED ISSUE #111: Add option to set visibility of Swift protobuf
See https://github.com/rules-proto-grpc/rules_proto_grpc/discussions/97

### PR DESCRIPTION
**Pull request by aaliddell**
Tracking PR for changes pending for 3.0.0.

- Dependencies updated
- Merged #98 
- Merged #103
- Merged #110
- Closes #108
- Closes #67 
- Closes #66 
- Closes #55
- Closes #68
- Closes #25
- Closes #31 
- Closes #85 
- Closes #111
- Closes #54
- Closes #105
- Closes #59
- Closes #72 
- Closes #93 
- Closes #20
- Closes #40

Pending external issues:
- ~~https://github.com/grpc-ecosystem/grpc-gateway/pull/1972~~
- https://github.com/bazelruby/rules_ruby/issues/86
- https://github.com/bazelbuild/rules_dotnet/issues/225

### CODE REVIEW

**Comment by ash2k** [comment]
@aaliddell Hey, thanks a lot for working on this! I was able to migrate my project to the `dev` branch! If you are curious, here is the PR https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/merge_requests/256

I have a small piece of feedback - would be nice to be able to define plugins with or without support for the legacy (`deps`) mode. I don't need to support it so it might be beneficial to drop it to avoid any aspect running costs. It's probably trivial, but I ran out of time to tinker with it.

**Comment by aaliddell** [comment]
> @aaliddell Hey, thanks a lot for working on this! I was able to migrate my project to the `dev` branch! If you are curious, here is the PR https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/merge_requests/256

Awesome, thanks for testing and the feedback. If there was anything particularly painful in the migration let me know and perhaps there's something I can do to ease it.

The release shouldn't be too far off now, just a few more things to merge and fix. Knowing my luck that'll be another 7 day rabbit hole of dependency chasing :rabbit: 

> I have a small piece of feedback - would be nice to be able to define plugins with or without support for the legacy (`deps`) mode. I don't need to support it so it might be beneficial to drop it to avoid any aspect running costs. It's probably trivial, but I ran out of time to tinker with it.

We should actually be able to drop the aspect on the protos attr without breaking anything, since that was put there during the transition in this PR where originally the non-transitive mode pulled the outputs from the aspect generated provider. Since the non-transitive mode now invokes protoc directly, the aspect on protos may actually be useless. I shall test.

Either way, if the transition goes well I intend to drop the aspect completely in a later major release, whenever that may be.

**Comment by aaliddell** [comment]
There's your answer, you can just drop the aspect and provider on the protos attr. And if you're using protos attr, the deps attr aspect will never be given anything to be called on, so you don't pay for it if you don't use it. Thanks for spotting :+1:

**Comment by aaliddell** [comment]
:partying_face:

**Pull request merged**
