### PR TITLE
Update C# rules

### PR DESCRIPTION
**Pull request by purkhusid**
## What?
Updates the C# rules to the latest version of rules_dotnet

## Why?
The latest version of rules_dotnet has gone through significant refactoring after dropping .Net Framework and Mono support and these rules need to be updated to be compatable

### CODE REVIEW

**Comment by purkhusid** [comment]
Should be ready for review @aaliddell

**Comment by aaliddell** [comment]
Awesome, thanks for the PR.
Just when I thought I'd caught up with pulling latest commits from other repos, there's another big change :laughing: 

I'm going to have to check how the overriding of platforms is going to work with the 'build and test all' CI task, which has some other issues presently that may be masking platform related troubles.

Also, the changes made to the presubmit flags will get overwritten when rulegen is run. This should have been flagged by the diff CI check, which I don't have set to run on PRs to other branches :man_facepalming:.

**Comment by purkhusid** [comment]
@aaliddell I also added a commit that fixes an issue with remote execution. I can split it into another PR if you prefer.
Context here: https://github.com/bazelbuild/bazel/issues/6393

**Comment by aaliddell** [comment]
> @aaliddell I also added a commit that fixes an issue with remote execution. I can split it into another PR if you prefer.
> Context here: [bazelbuild/bazel#6393](https://github.com/bazelbuild/bazel/issues/6393)

Is it this commit b48fadd805d47235237e91659d765a4e37dc79a9? I don't mind it being in here.

Once I've got gRPC gateway fixed to make CI green in dev branch I'll be looking to merge this.

**Comment by aaliddell** [comment]
Pending on https://github.com/bazelbuild/rules_dotnet/issues/225, since overriding the platforms is a significant requirement that may be avoidable.

**Pull request merged**
