### PR TITLE
Adding "use_built_in_shell_environment" as optional argument.

### PR DESCRIPTION
**Pull request by amitz**
Done. Feel free to modify the argument name/doc if you wish. Also, you might want to add a verbose print if that argument is set to True or False (I didn't want to modify your debug settings).

### CODE REVIEW

**Comment by amitz** [comment]
There's a single test failure, but this doesn't seems to be related to the pull-request?

**Comment by amitz** [comment]
I added another thing for you to consider. The option `java_conversions` generates converters to/from the Java protocol buffers. We find it quite useful on our projects, and I have seen it in other project.

I added this option into the BUILD file directly, but I'm not too happy with it because while very useful - I'm not sure everyone will want to use it. Is there a way to set you own options from within the rule?

**Comment by aaliddell** [comment]
Thanks :+1:

I may update the plugin flag name to match the underlying `use_default_shell_env` flag name.

The failing test is also failing on master, as it looks like the Mac CI environment was updated and broke rules_d.

**Comment by amitz** [comment]
Sure, I went with the description of "use_default_shell_env" in the official Bazel [documentation](https://docs.bazel.build/versions/master/skylark/lib/actions.html), as `use_default_shell_env` wasn't very clear for me, but both works to be honest :-)

Thanks!

**Pull request merged**
